### ISSUE TITLE
[Bug]: cannot search (o ... search)

### ISSUE THREAD

**Issue by boxcounter** [chrisgrieser/shimmering-obsidian#108] opened 2023-01-03 01:49 UTC
### Bug Description

cannot search using `o ...`

<img width="764" alt="image" src="https://user-images.githubusercontent.com/4317474/210290707-de08a329-8241-496c-b49b-c9ac9f7b573d.png">

### Relevant Screenshot

![image](https://user-images.githubusercontent.com/4317474/210290133-e55b5740-c610-4c22-a482-14f76c7e14dc.png)

### Debugging Log

```Text
[09:30:39.782] Logging Started...
[09:30:42.331] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[09:30:42.616] Shimmering Obsidian[Script Filter] Script with argv '(null)' finished
[09:30:42.621] ERROR: Shimmering Obsidian[Script Filter] Code 1: /Users/boxcounter/Alfred.alfredpreferences/workflows/user.workflow.B844E779-37E6-4BDB-8178-E9B075D501F3/scripts/o_search.js: execution error: Error: SyntaxError: JSON Parse error: Unexpected EOF (-2700)
[09:37:27.490] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[09:39:39.871] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

### Workflow Configuration 1

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/4317474/210290465-3cae8511-f303-4246-9ed9-fdb75dd612b9.png">

### Workflow Configuration 2

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/4317474/210290480-f3d3cc50-de13-41ec-bfac-f47d72313f88.png">

### Version & System Information

```Text
- macOS: 13.1 (22C65)
- Obsidian: 1.1.9
- Alfred: v5.0.6 [2110]
- Shimmering-obsidian: v.3.3.0
- Advanced URI: v1.31.2
- Metadata Extractor: v1.1.0
```

### Make sure you have done the following

- [X] I have [updated to the latest version](https://github.com/chrisgrieser/shimmering-obsidian/releases/latest) of this workflow.
- [X] I have read the [Troubleshooting Documentation](https://github.com/chrisgrieser/shimmering-obsidian/blob/main/docs/Troubleshooting.md).
- [X] If the `o…` main search does not work, I have tried rerunning `osetup` and it still does not work.
- [X] If I updated to version 3+ for the first time, I have disabled migrating workflow cutomizations. (If you haven't, you can simply re-download and install the latest release from GitHub and uncheck `Migrate my workflow customizations`.)

**Comment by chrisgrieser** [comment] 2023-01-03 07:47
could you add the full output of the `oinfo` command?

**Comment by cjinfantino** [comment] 2023-01-03 13:34
This also did not work for me with 3.3.0 or 3.2.3. It was when I downgraded to 3.2.2 that it started working as expected.

**Comment by chrisgrieser** [comment] 2023-01-03 13:59
what started working as expected? `oinfo`? `o` search in general? If the former, please add the output of the `oinfo` command

**Comment by chrisgrieser** [comment] 2023-01-03 18:38
thanks for the thorough retracing! I have added some extra safety-nets to handle this stuff, so the issue should not occur anymore.

**Comment by boxcounter** [comment] 2023-01-04 01:54
Hi, chrisgrieser. I've installed v3.3.2, Neither `oinfo` no `o ...` worked for me.

Steps：
1. uninstall 3.3.0
2. install 3.3.2
3. run `oinfo`, no output in clipboard
4. run `osetup`, choose the only vault. Obsidian restarted automatically, and Alfred popped up a failure hint and suggested me to run `oupdate`. (picture 1)
5. run `oupdate`, Alfred popped up a succuessful hint. (picture 2)
6. run `oinfo`, still no ouput.
7. run `o ...` , search did not work neither.


picture 1:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4317474/210469261-f5a7a7d4-d8a0-4b48-a4b3-65069c766321.png">

picture 2:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4317474/210469447-041c9d9e-162b-454f-abee-e39bb5a9716f.png">

debug log:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/4317474/210470213-460a4ba3-3fbc-49b4-89d0-efd3aa211fea.png">

**Comment by cjinfantino** [comment] 2023-01-04 02:01
@boxcounter have you tried installing 3.2.2 first and seeing if that works? I haven't dug in, but that's when it started working for me, and one thing I noticed was with 3.3.0, it appeared to be missing some of the workflows. When I installed 3.2.2 and looked in Alfred I noticed all the workflows and hotkey. 

Again, I have no idea if it's the answer, as I didn't dig in too much. 

I would try: 

1. Install 3.2.2 in-place
2. Test
3. If it works upgrade in-place to 3.3.2 
4. Test

**Comment by chrisgrieser** [comment] 2023-01-04 02:13
@boxcounter from your debugging log, it looks like the writing of the metadata wasn't successful.

Could you run `Metadata Extractor: Write JSON File to disk.` from the command palette and then try again `o` and `oinfo`?

**Comment by chrisgrieser** [comment] 2023-01-04 02:19
oh, another potential issue might be if you named your Obsidian config folder to something other than `.obsidian`

**Comment by boxcounter** [comment] 2023-01-04 02:39
> @boxcounter from your debugging log, it looks like the writing of the metadata wasn't successful.
> 
> Could you run `Metadata Extractor: Write JSON File to disk.` from the command palette and then try again `o` and `oinfo`?
> 
> Also, could you show your environment variables again, now after the re-installation?

`o ...` and `oinfo` did not work after `Metadata Extractor: Write JSON file with metadata to disk` run. 
![image](https://user-images.githubusercontent.com/4317474/210473665-ca783828-82e9-4271-b7f6-869c63b938d0.png)

Enviroment variables are:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/4317474/210473956-b941acf8-a99f-4515-9570-96403c1578fc.png">


And Obsidian config folder is left untouched:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/4317474/210473889-8f8d00d7-6220-49fa-a355-ecc0aab745f4.png">

And Metadata Extractor setting is left unchanged:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/4317474/210474336-8f8e6440-4f45-4963-97cd-05dbf3c79749.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/4317474/210474381-c62a1833-25de-4dcc-8232-7e1a606ff404.png">

**Comment by chrisgrieser** [comment] 2023-01-04 02:59
> And Metadata Extractor setting is left unchanged:

hah, that's the issue though, they should be untouched by *you*, but the Alfred workflow *should* touch them. (that's what the restart on `osetup` does, or at least is supposed to do.)

by having periodic writing and writing on launch disabled, the metadata never gets written, which is also consistent with the debugging log further above.

**Comment by boxcounter** [comment] 2023-01-04 05:47
hah, thanks for your explanation, chrisgrieser. I got it.

Is there anything I can do to help you fix this issure?

**Comment by chrisgrieser** [comment] 2023-01-04 11:11
unfortunately, I do not really have any idea what's causing this, and as long as I cannot reproduce it, it's not really easy to think of something

**Comment by Vlahn** [comment] 2023-01-07 14:58
I know it's not helpful to not submit any additional info for a bug report.. However, I really wanted to add to the existing reports above to say that I too am experiencing this issue (keyword: 'o' not working). I also have the experience of the 'metadata export' failing to work as the workflow expected and needing to manually trigger it (which is reported to succeed).
1. I have followed the various steps described above (unchecked retain settings on workflow import, osetup, oupdate etc)
2. I have tried installing 3.2.2 and it has not helped either
3. I have tried removing the workflow and reinstalling without any success either. 

I am on an M1 Mac. I am using a current public build of Obsidian (1.1.9).

**Comment by chrisgrieser** [comment] 2023-01-08 04:09
okay, I have rewritten larger parts of the workflow to avoid issue an Alfred method for reading config data. Now running `osetup` *should* work far more reliably.

**Comment by boxcounter** [comment] 2023-01-18 05:58
Hi, it happened again after I upgraded it to v3.5.3. 
And like before, works after I degraded to v3.2.2.

**Comment by chrisgrieser** [comment] 2023-01-18 11:13
yeah, I cannot really fathom what could cause that issue. 

The only thing I could think of is an Obsidian-side issue from the migration von 0.x to 1.x. You can quit Obsidian, delete `workspace` and/or a `workspace.json` file in `{vaultpath}/.obsidian` (hidden folder, can be made visible with `cmd+shift+.`), start Obsidian again and then try whether `osetup` works. (This will only delete your current workspace, meaning your sidebar tabs will be reset and you will have to add your tabs there manually again.)

---

If that does not help, I think creating a new bug report would be best. Since larger parts of the workflow have been rewritten with 3.5, I'd need the new debugging logs, the new `oinfo` output etc from the latest version to determine what could still be causing this – basically I'd need a fresh set of all the debugging-related information before I can really do anything.

**Comment by chrisgrieser** [comment] 2023-02-03 16:19
closing this since I assume it's fixed. And if not, someone with this issue needs to submit a new bug report form, since I'd need the debugging logs with the new version anyway

**Closed by chrisgrieser** 2023-02-03 16:19 UTC
Labels: bug, not reproducible
