### ISSUE TITLE
Feature Request: Support Obsidian Advanced URI in Open Daily Note

### ISSUE THREAD

**Issue by n3bulous** [chrisgrieser/shimmering-obsidian#33] opened 2021-12-04 23:17 UTC
**Feature Requested**

By changing your `od` Open URL to `obsidian://advanced-uri?daily=true` it will open, or create (I couldn't figure out how to do this currently), a new note with the specified template configured in Daily Note.

The simple change would require using the Daily Note plugin, however.  Perhaps a toggle config?

**Checklist**
- [x] The feature would be useful to more users than just me.
- [x] I have checked the [feature overview](https://github.com/chrisgrieser/shimmering-obsidian#feature-overview) and the feature doesn't already exist.
- [ ] If it is an entirely new feature and not just a feature improvement: The requested feature makes more sense to be implemented in Alfred than in a plugin. (Please briefly outline why you think so!)

**Comment by chrisgrieser** [comment] 2021-12-04 23:33
I will definitely implement this since more daily note capabilities are basically the number one request. But when I do it, I want to implement it properly and in a more comprehensive way than just changing the URI, which will take a bit of time. 

I'll implement all the daily note feature requests and improvements some time soon all in one go.

Basically a duplicate of #22, therefore closed.

**Closed by chrisgrieser** 2021-12-04 23:33 UTC
Labels: duplicate, enhancement, daily notes
