### ISSUE TITLE
[BUG] OCR not working on macOS Mojave

### ISSUE THREAD

**Issue by AngelusDomini** [chrisgrieser/shimmering-obsidian#15] opened 2021-09-06 17:15 UTC
I've set up my vault path and installed the requirements for this feature. When I OCR something, Obsidian opens the OCR-Screenshot note, but it's empty except for the divider thingy `---` and the prefix. I forgot to do the part where I give Alfred permission to record the screen. When I checked, there is no setting for the screen recording as shown in your screenshot. Apparently, this setting was just included in Catalina (10.15), and I'm using Mojave (10.14).

I was wondering if this issue can be fixed for Mojave, and also whether you are willing to fix it :3

**Comment by chrisgrieser** [comment] 2021-09-08 07:54
well, I'd happily fix it, but granting permission to an app isn't something I can do, as that is something every end user has to do on their own (I mean, that's the very idea of "granting permission" ;) )

I tried googling how the permission granting worked in Mac OSX 10.14, but boy, it is surprisingly hard to find any solid information on this, since all tech blogs seem to update their guides quickly to the newer mac versions. So I can unfortunately only take a guess how it work, but I *think* you should also be able to grant Alfred permission by adding the Alfred app manually to the list of app permitted to take screenshots.

<img width="333" alt="Screenshot 2021-09-08 09 49 36" src="https://user-images.githubusercontent.com/73286100/132468854-382359b5-3b69-4949-97a4-99c9a6e1ecd5.png">

If after adding Alfred here, please follow the instructions in the [Troubleshooting Section](https://github.com/chrisgrieser/shimmering-obsidian#troubleshooting) and copypaste your debugging-log, so I can figure out what the issue is.

**Comment by AngelusDomini** [comment] 2021-09-09 11:10
Hey, thanks for responding. The problem is that there is no Screen Recording category in my privacy tab. It seems that this is only available for Catalina and Big Sur.

![Screen Shot 2021-09-09 at 6 40 16 PM](https://user-images.githubusercontent.com/59588053/132673245-d2114538-a401-4233-8fa0-bc40503dbf25.png)
![Screen Shot 2021-09-09 at 6 40 23 PM](https://user-images.githubusercontent.com/59588053/132673232-82eb4e16-9dee-4003-962f-76d3c670a35b.png)

However, I think Alfred already has permission to take screenshots. When I use the workflow's OCR feature, the mouse cursor for the Cmd+Shift+4 screenshot appears, and it makes the screenshot sound when I click. It's just that none of the text that I screenshot'd appears in the OCR note

![Screen Shot 2021-09-09 at 6 55 13 PM](https://user-images.githubusercontent.com/59588053/132673666-c11b3a24-998b-4ce0-95cc-ba7e2201f8d2.png)

Here's the debugging log (pardon the username lol):
```
[18:58:47.567] Logging Stopped.
[18:58:51.899] Logging Started...
[18:59:02.531] Shimmering Obsidian[Run Script] Processing complete
[18:59:02.532] Shimmering Obsidian[Run Script] Passing output '' to Conditional
[18:59:02.539] Shimmering Obsidian[Run Script] Passing output '' to Run Script
[18:59:08.578] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[18:59:08.591] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
[18:59:10.086] Shimmering Obsidian[Keyword] Processing complete
[18:59:10.093] Shimmering Obsidian[Keyword] Passing output '' to Run Script
[18:59:29.449] Shimmering Obsidian[Run Script] Processing complete
[18:59:29.472] Shimmering Obsidian[Run Script] Passing output '' to Replace
[18:59:29.482] Shimmering Obsidian[Replace] Processing complete
[18:59:29.484] Shimmering Obsidian[Replace] Passing output '' to Replace
[18:59:29.486] Shimmering Obsidian[Replace] Processing complete
[18:59:29.488] Shimmering Obsidian[Replace] Passing output '' to Transform
[18:59:29.490] Shimmering Obsidian[Transform] Processing complete
[18:59:29.492] Shimmering Obsidian[Transform] Passing output '' to Write Text File
[18:59:29.494] Shimmering Obsidian[Write Text File] Processing complete
[18:59:29.496] Shimmering Obsidian[Write Text File] Passing output '/Users/deeznuts/Google Drive/Slippy Box/OCR-Screenshot.md' to Call External Trigger
[18:59:29.498] Shimmering Obsidian[External] Processing complete
[18:59:29.500] Shimmering Obsidian[External] Passing output '/Users/deeznuts/Google Drive/Slippy Box/OCR-Screenshot.md' to Run Script
[18:59:29.501] Shimmering Obsidian[Transform] Passing output '' to Copy to Clipboard
[18:59:29.505] Shimmering Obsidian[Copy to Clipboard] Processing complete
[18:59:29.507] Shimmering Obsidian[Copy to Clipboard] Passing output '' to Post Notification
[18:59:34.648] Shimmering Obsidian[Run Script] Processing complete
[18:59:34.651] Shimmering Obsidian[Run Script] Passing output '/Users/deeznuts/Google Drive/Slippy Box/OCR-Screenshot.md
' to Replace
[18:59:34.653] Shimmering Obsidian[Replace] Processing complete
[18:59:34.655] Shimmering Obsidian[Replace] Passing output '/Users/deeznuts/Google Drive/Slippy Box/OCR-Screenshot.md' to Run Script
[18:59:59.937] Shimmering Obsidian[Run Script] Processing complete
[18:59:59.970] Shimmering Obsidian[Run Script] Passing output '' to Run Script
[19:00:22.051] Shimmering Obsidian[Run Script] Processing complete
[19:00:22.054] Shimmering Obsidian[Run Script] Passing output '' to Conditional
[19:00:22.056] Shimmering Obsidian[Run Script] Passing output '' to Run Script
```

Thanks for your help! Let me know if there's anything else I can help with here

**Comment by chrisgrieser** [comment] 2021-09-09 12:09
Hmm. could you check whether you have valid language codes set in the `ocr_languages` setting?

If you have, could you try running the following command in your Terminal? It basically does the the same as the Alfred workflow, but hopefully gives more of a clue what is going on on your side.
```bash
screencapture -i test.png && tesseract test.png stdout
```

**Comment by AngelusDomini** [comment] 2021-09-09 13:29
Yes, the language codes I've used come from the list of supported languages you provided from the instructions. I also tried it with just `eng` and the text still doesn't appear.

The terminal command does give a clue. When I run it and do the screenshot, it shows:

![image](https://user-images.githubusercontent.com/59588053/132694234-646a76ac-ee5b-4af3-84ce-ef7c16dd757e.png)

FWIW I already installed tesseract-lang, and the terminal insisted that I already have it installed when I tried to install it again a few hours ago. When I run `tesseract --list-langs`, it shows the same error as the command line you gave me.

**Comment by chrisgrieser** [comment] 2021-09-09 13:59
okay, that means there is some issue with your tesseract installation. From what I can tell from [this stackoverflow post](https://stackoverflow.com/a/14269066), that error could mean that your Mac might be too old to run tesseract. 😕 

You could try to ask in the [tesseract user group](https://groups.google.com/g/tesseract-ocr) if there is something you can. Otherwise, I am afraid there is nothing we can do, expect you upgrading your Mac, sorry 🙁

(Closing this issue, since it is confirmed that this not an issue with _Shimmering Obsidian_.)

**Closed by chrisgrieser** 2021-09-09 13:59 UTC
Labels: bug
