### ISSUE TITLE
[BUG] Use ⇧ + ↵ on any search result of the main o search to browse the links of that note don‘t work

### ISSUE THREAD

**Issue by Miaoyifei-mz** [chrisgrieser/shimmering-obsidian#38] opened 2021-12-12 07:41 UTC
**Hello, this workflow is amazing, thank you a lot!**, here are some of the bugs I encountered using this workflow.
As mentioned in the topic，when I  press ⇧ + ↵, nothing ever happend.

https://user-images.githubusercontent.com/60280844/145703909-6c299a04-06f6-479d-93a9-5e2d183c7949.mp4

But when I press ⇧ + ↵ in  `ol` , it works. 

https://user-images.githubusercontent.com/60280844/145704099-c1508c6d-c0d0-4776-bbac-d4b8add72ba8.mp4

In addition，When I press ↵ in `ot` to select notes, this workflow seems to have stopped.

https://user-images.githubusercontent.com/60280844/145704181-542d2add-3ccb-49ae-abac-517d62463055.mp4

The same thing happens in the search folder.

https://user-images.githubusercontent.com/60280844/145704236-255906b7-e29c-4b6f-be2e-fb29a75bcb30.mp4

**Below is the running information in Alfred when I  press ⇧ + ↵**

```
[15:31:36.582] Shimmering Obsidian[Script Filter] Processing complete
[15:31:36.583] Shimmering Obsidian[Script Filter] Passing output '1-学习笔记/科研生活/卡片笔记法.md' to Call External Trigger
[15:31:36.584] Shimmering Obsidian[External] Processing complete
[15:31:36.584] Shimmering Obsidian[External] Passing output '1-学习笔记/科研生活/卡片笔记法.md' to Arg and Vars
[15:31:36.585] Shimmering Obsidian[Arg and Vars] Processing complete
[15:31:36.585] Shimmering Obsidian[Arg and Vars] Passing output ' ' to Script Filter
[15:31:36.604] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

**Below is the running information in Alfred when I press ↵ in `ot` to select notes**

```
[15:38:57.931] Shimmering Obsidian[Script Filter] Processing complete
[15:38:57.932] Shimmering Obsidian[Script Filter] Passing output 'zotero' to Arg and Vars
[15:38:57.932] Shimmering Obsidian[Arg and Vars] Processing complete
[15:38:57.932] Shimmering Obsidian[Arg and Vars] Passing output ' ' to Script Filter
[15:38:57.933] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

**Below is the running information in Alfred when I press ↵  to search folders**

```
[15:40:25.807] Shimmering Obsidian[Script Filter] Processing complete
[15:40:25.808] Shimmering Obsidian[Script Filter] Passing output '2-工作文档' to Call External Trigger
[15:40:25.808] Shimmering Obsidian[External] Processing complete
[15:40:25.809] Shimmering Obsidian[External] Passing output '2-工作文档' to Arg and Vars
[15:40:25.809] Shimmering Obsidian[Arg and Vars] Processing complete
[15:40:25.810] Shimmering Obsidian[Arg and Vars] Passing output '2-工作文档' to Arg and Vars
[15:40:25.810] Shimmering Obsidian[Arg and Vars] Processing complete
[15:40:25.810] Shimmering Obsidian[Arg and Vars] Passing output '2-工作文档' to Conditional
[15:40:25.811] Shimmering Obsidian[Conditional] Processing complete
[15:40:25.811] Shimmering Obsidian[Conditional] Passing output '2-工作文档' to Call External Trigger
[15:40:25.811] Shimmering Obsidian[External] Processing complete
[15:40:25.812] Shimmering Obsidian[External] Passing output '' to Script Filter
[15:40:25.812] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

**Comment by chrisgrieser** [comment] 2021-12-12 14:41
I have a suspicion what the cause might be, possibly this is also the same underlying cause as #25

**Comment by chrisgrieser** [comment] 2021-12-12 16:14
I think the issue is related to something with Asian characters not read properly. However, since I am not too familiar with such issues, I am not totally sure. I have changed some stuff which *potentially* fixes the issue for `ot` and `ol`. 

Could you update to 2.9.8 and confirm whether `ot` and `ol` are working for you?

(the opening of folders is a bit more complicated to implement, wanna confirm that this is the cause first.)

**Comment by Miaoyifei-mz** [comment] 2021-12-13 01:55
Hi, I update to 2.9.8, but the issue still remains. In addition, I switch vault to `obsidian help` (it has no Asian characters) to test, unfortunately, the issue doesn't be fixed.

**Comment by chrisgrieser** [comment] 2021-12-13 02:11
have you installed the metadata extractor and the advanced URI plugin both in the help vault and then run `osetup`?

If the issue still persists with the help vault then, could you try to create a "minimal" vault out of it, ideally with only a handful of documents and send me an archive of that vault? 

And if the problem does not persist and and seemingly only persists with non-western characters, could you try to create a "mini-vault" with some non-western document names (and the metadata extractor and advanced uri plugin)?

Thing is, as long as I cannot reproduce the issue, I cannot do much to fix it, so I need some kind of vault where I can reproduce the issue.

**Comment by Miaoyifei-mz** [comment] 2021-12-13 02:59
Yes, I installed the metadata extractor and the advanced URI plugin both in the help vault and then run `osetup`. The issue still persists, I create a "minimal" vault out of it, you can download from [this link](https://cowtransfer.com/s/c847dbaa86d649).
Thanks again! ☺

**Comment by chrisgrieser** [comment] 2021-12-13 03:07
Great, thanks! :) 
I'll look into it, but it might take a till Christmas break, since I have got a lot of stuff to do at work before.

**Comment by Miaoyifei-mz** [comment] 2021-12-13 04:10
Ok, hope your work goes well! :)

**Comment by Miaoyifei-mz** [comment] 2021-12-14 03:05
Hello,I'm very  sorry to bother you again. When I search for Headings, there is something wrong: 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/60280844/145925198-a87ffb05-c17e-4e2e-945c-656da95467a5.png">
But when I search for notes, it works.
Do I need to set more something  in the Advanced URL or workflow?

**Comment by Miaoyifei-mz** [comment] 2021-12-14 03:06
<img width="296" alt="image" src="https://user-images.githubusercontent.com/60280844/145925843-4754f1ba-f6a7-4744-bfe3-5dfc048834fa.png">

**Comment by chrisgrieser** [comment] 2021-12-14 03:16
Hi, I created a new issue for this, since it looks like a separate problem and I cannot keep track of things when they are all in one issue :)
➞ issue #39

**Comment by chrisgrieser** [comment] 2021-12-14 16:42
Okay, I have found and fixed a bug for the link-browsing via `shift + return` and the `ol` which *sometimes* causes it to fail. Could you check whether it works now? (version 2.9.12)

**Comment by Miaoyifei-mz** [comment] 2021-12-15 02:07
Thank you! Unfortunately, it doesn't work (The same is true for the `Obsidian Help` vault). Here is the debug log for the link-browsing via `shift + return`

```
[09:58:54.837] Shimmering Obsidian[Script Filter] Processing complete
[09:58:54.838] Shimmering Obsidian[Script Filter] Passing output '1-学习笔记/科研生活/卡片笔记法.md' to Call External Trigger
[09:58:54.838] Shimmering Obsidian[External] Processing complete
[09:58:54.839] Shimmering Obsidian[External] Passing output '1-学习笔记/科研生活/卡片笔记法.md' to Write Text File
[09:58:54.839] Shimmering Obsidian[Write Text File] Processing complete
[09:58:54.840] Shimmering Obsidian[Write Text File] Passing output '/Users/zhuangzhu/Library/Application Support/Alfred/Workflow Data/de.chris-grieser.shimmering-obsidian/buffer_inputPath' to Arg and Vars
[09:58:54.840] Shimmering Obsidian[Arg and Vars] Processing complete
[09:58:54.840] Shimmering Obsidian[Arg and Vars] Passing output '' to Script Filter
[09:58:54.841] Shimmering Obsidian[Script Filter] Queuing argument '(null)'
```

**Comment by chrisgrieser** [comment] 2021-12-15 02:25
Hi! I tried it out with your test vault and for me, the workflow works flawlessly.

Could you describe what situation *exactly* where the workflow doesn't work for you?
https://user-images.githubusercontent.com/73286100/146111442-f6c1ef74-7aa0-4e44-906e-485a6c814208.mov

**Comment by Miaoyifei-mz** [comment] 2021-12-15 03:05
Hello！This is the workflow running on my computer：

https://user-images.githubusercontent.com/60280844/146115195-85a82873-c2e8-46c7-a871-b5d9b17fdcbd.mp4

As you can see in the video，when I press the `return+shift`, the workflow seemly stopped, the `ol` option box didn't appear.

**Comment by Miaoyifei-mz** [comment] 2021-12-15 03:08
But when I first type `ol` to find the links in the current notes, the `return+shift` can work.

**Comment by Miaoyifei-mz** [comment] 2021-12-19 06:44
Hello, I just tested this issue on my classmate's new Mac. The Shimmering -obsidian runs perfectly. So, it seems that there are some problems on my Mac. This issue is a special case. Perhaps it will be fixed  in a later version without a reason. After all, life is full of surprises😂.

**Comment by chrisgrieser** [comment] 2021-12-19 13:17
okay, that is indeed weird. Maybe it's an issue with an old mac or something? Maybe an outdate version of Alfred?

Well, since it seems not to be an issue related to this workflow, I am closing this. Feel free to re-open this or open a new issue, if you find out that it is an issue with this workflow, after all!

**Closed by chrisgrieser** 2021-12-19 13:17 UTC
Labels: bug
